service: wl-node-rest

plugins:
  - serverless-offline

custom:
  tableName: 'wines-table-${self:provider.stage}'

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  vpc:
    securityGroupIds:
      - sg-63505b11
    subnetIds:
      - subnet-866b33ff
      - subnet-c6ddf69c
      - subnet-7ec6bc35
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rds:*
        - cloudwatch:*
        - logs:*
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource: "*"
  environment:
    RDS_HOST: ${ssm:/jmswinelist/rds.host}
    RDS_PSWD: ${ssm:/jmswinelist/rds.pswd}
    RDS_USER: ${ssm:/jmswinelist/rds.user}

package:
  exclude:
    - jmswines.csv
    - schema.sql
    - wines.json

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getAllWines:
    handler: index.handler
    events:
      - http: 'GET /wines'
    timeout: 15
  getWine:
    handler: index.handler
    events:
      - http: 'GET /wines/{proxy+}'
  createWine:
    handler: index.handler
    events:
      - http: 'POST /wines'